name: Context Engine Tests

on:
  push:
paths:
  - 'supabase/migrations/**'
  - 'tests/e2e/context-engine/**'
  - 'apps/web/app/demo/**'
  pull_request:
paths:
  - 'supabase/migrations/**'
  - 'tests/e2e/context-engine/**'
  - 'apps/web/app/demo/**'

jobs:
  test-context-engine:
timeout-minutes: 15
runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v4
  
  - name: Setup Node.js
uses: actions/setup-node@v4
with:
  node-version: '20'
  
  - name: Enable Corepack
run: corepack enable

  - name: Install dependencies
run: yarn install --immutable

  - name: Install Playwright Browsers
run: yarn playwright install --with-deps chromium

  - name: Setup Supabase CLI
uses: supabase/setup-cli@v1
with:
  version: latest
  
  - name: Start Supabase local stack
run: |
  supabase start --workdir ./supabase
  supabase db push --workdir ./supabase
env:
  SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
  
  - name: Run Context Engine Tests
run: yarn playwright test context-engine/
env:
  SUPABASE_URL: http://localhost:54321
  SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
  
  - uses: actions/upload-artifact@v4
if: failure()
with:
  name: test-results
  path: test-results/
  retention-days: 7